#!/bin/bash
SYSROOT_DIR="{SYSROOT_PLACEHOLDER}"

export PKG_CONFIG_PATH=
export PKG_CONFIG_LIBDIR=${SYSROOT_DIR}/lib/pkgconfig:${SYSROOT_DIR}/share/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=${SYSROOT_DIR}

exec pkg-config "$@"
